### ISSUE TITLE
GitHub Pages deployment links to incorrect paths

### ISSUE THREAD

**Issue by ChrisNeedham24** [jamesgiu/quick-hit#11]
While the links within the app work, if you refresh any of the non-home pages, you'll get a 404.

**Comment by jamesgiu** [comment]
Yeah it does, we should be able to prepend routes with the  'quick-hit' path to cheese this and get around it 😂

I'm gonna do a bunch of tidy up tonight including a few bug fixes so I might include it (unless you're already on it)

**Comment by ChrisNeedham24** [comment]
> Yeah it does, we should be able to prepend routes with the 'quick-hit' path to cheese this and get around it 😂
> 
> (Though the real solution would probably entail using process env variables for deploy vs start and have it change the base path for a GH pages deployment)
> 
> I'm gonna do a bunch of tidy up tonight including a few bug fixes so I might include it (unless you're already on it)

I was planning on doing it but go right ahead. That's the way I was thinking of doing it anyway haha

**Comment by jamesgiu** [comment]
Oh dude ❤️! If you free up and are itching for more, feel free to go for it 👍

You shoild be able to deploy to GH pages with `npm run deploy`

**Comment by jamesgiu** [comment]
So I merged some changes to do with setting a configurable base path, still works, but didn't solve the problem. I reckon it's a GH pages thing now
