### ISSUE TITLE
Show involved player on graph coordinate

### ISSUE THREAD

**Issue by jamesgiu** [jamesgiu/quick-hit#139]
On the coordinate hover, some info is displayed, it'd be cool to see the involved player for that particular coordinate

The example was that I saw Needham had a very rare dip during his ascendance and you have to sift through the recent games to find out who was responsible. 

The twist is though, the dip was actually a win, and his ELO was robbed due to a QH bug at the time (now fixed).

**Comment by ChrisNeedham24** [comment]
Yeah it does look odd with the dip haha but the ELO wasn't actually robbed, the match just didn't record it properly, so the next game it looks like I got double ELO but it was really just one game.
