### ISSUE TITLE
Firebase auth quota limit

### ISSUE THREAD

**Issue by jamesgiu** [jamesgiu/quick-hit#33]

**Comment by ChrisNeedham24** [comment]
After doing some research on this, I'm not sure that we can actually do anything about this, while we're all using the same account. The limit is 25 requests in 10 minutes, which isn't that low, but still. So yeah, if we want to address this, we'd need to add multiple accounts, I think.

**Comment by jamesgiu** [comment]
Yeah I guess we'll close this until it becomes a huger issue, though we could do some cheeky account rotation in the background if we have to

**Comment by jamesgiu** [comment]
Thanks for looking into it btw

**Comment by jamesgiu** [comment]
IT'S BACK

**Comment by ChrisNeedham24** [comment]
Could also modify the polling with this one.

**Comment by ChrisNeedham24** [comment]
🦀
