### ISSUE TITLE
"close losses" , "close wins" stat

### ISSUE THREAD

**Issue by jamesgiu** [jamesgiu/quick-hit#40]

**Comment by ChrisNeedham24** [comment]
Maybe a badge/achievement if you win/lose a certain number of close games? "Clutch performer" maybe for the close winner one, and "Heart Breaker" for the close loser one?

**Comment by jamesgiu** [comment]
Yeah that's good too, this was more of a numeric thing on the profile but I don't see why we can't reuse the calculation for that as well

**Comment by jamesgiu** [comment]
The badge thing is working out well actually, this'll just clutter up the page more so maybe we keep it to badges
