### ISSUE TITLE
All time high/low ELOs

### ISSUE THREAD

**Issue by ChrisNeedham24** [jamesgiu/quick-hit#5]

**Comment by jamesgiu** [comment]
Nice dude!  Looks awesome, just saw the deployed version. Might make an issue to use GH CI/CD to make it auto-deploy every time a PR is merged or something?? That'd be sweet.

I've got a refactor idea that we can bust out at some point (maybe if the app starts slowing down), my approach with this was to use the DB.

DB approach:
A match is entered, and then elo is calculated as usual, and if there are any all-time lows or highs for the players involved, record it in their player record. This saves some JS calculations on the client-side for when a player's profile is loaded by leveraging the information present when entering a game.

**Comment by ChrisNeedham24** [comment]
>DB approach:
A match is entered, and then elo is calculated as usual, and if there are any all-time lows or highs for the players involved, record it in their player record. This saves some JS calculations on the client-side for when a player's profile is loaded by leveraging the information present when entering a game.

Yep, good call. Eventually this will slow down, but it'll work for now.

**Comment by jamesgiu** [comment]
Yep, but still - lookin' good

**Comment by jamesgiu** [comment]
😍
