### ISSUE TITLE
Add percentages to achievements

### ISSUE THREAD

**Issue by ChrisNeedham24** [jamesgiu/quick-hit#57]
E.g. 30% of players have achieved this

**Comment by jasonlwj** [comment]
👋 Is this one still open? If so, put me on this 🚀

**Comment by jamesgiu** [comment]
👋  All yours I believe, feel free to assign yourself to the issue, GLHF

**Comment by jasonlwj** [comment]
[PR is up 🚀](https://github.com/jamesgiu/quick-hit/pull/86)

**Comment by ChrisNeedham24** [comment]
Just so you know @jasonlwj , in terms of QH code reviews, as a great man once said, "We don't do that here". I'll still take a quick look though.

**Comment by jamesgiu** [comment]
The best time to review the code is when fixing any bugs the code caused 😂

**Comment by ChrisNeedham24** [comment]
> The best time to review the code is when fixing any bugs the code caused 😂

Ain't that the truth
