### ISSUE TITLE
Width of cards is based on window height

### ISSUE THREAD

**Issue by wejrox** [jamesgiu/quick-hit#68]
Cards use the window height to set their width. Open the profile for a user and open dev tools on the bottom. That doesn't seem right.

**Comment by wejrox** [comment]
Issue seems to be in PlayerCard.css .ui.card.player-card using `vh` for some reason.

**Comment by ChrisNeedham24** [comment]
Turns out this also occurs in Ladder.css for the player cards, and for the happy hour popover.
