### ISSUE TITLE
Tournament generator

### ISSUE THREAD

**Issue by ChrisNeedham24** [jamesgiu/quick-hit#7]
Generate a tournament based on the current ladder. Could be weekly, monthly, etc. Could also add double elimination in future.

**Comment by jamesgiu** [comment]
Love it, even a tournament page that will have a generator if no tournaments are going OR the current tournament it one is going

**Comment by ChrisNeedham24** [comment]
I reckon I'll take a look at this as my first backend issue.

**Comment by jamesgiu** [comment]
Big tickie, will this include the tournament view + entering games to progress the tournament? Or just the generation?

**Comment by ChrisNeedham24** [comment]
> Big tickie, will this include the tournament view + entering games to progress the tournament? Or just the generation?

Mate, this is going to be the real deal. I'm going to keep all the stuff I'm implementing as a surprise for when it's done.

**Comment by jamesgiu** [comment]
I'm stoked man, can't wait 

(The next challonge)

**Comment by jamesgiu** [comment]
Nek minnet you outsource the tournament to challonge via API calls or something 😂

**Comment by ChrisNeedham24** [comment]
Damn, you figured me out
