### ISSUE TITLE
Custom achievement for winner of tournament

### ISSUE THREAD

**Issue by jamesgiu** [jamesgiu/quick-hit#76]
And for other finalist

E.g.

"Winner of Shoot One Out For Dave tournament"

**Comment by jasonlwj** [comment]
This could be interesting

gib

**Comment by jasonlwj** [comment]
Was kinda inactive but we're making some progress here -
![image](https://user-images.githubusercontent.com/8891030/126893325-d96f4e7a-5aeb-4bd9-b129-ed8230cbf7bd.png)
